### ISSUE TITLE
[Linux] stable/12.0.50 build needs to be removed

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/downloads.keyman.com#20]
The initial stable build 
https://downloads.keyman.com/linux/stable/12.0.50/ is incorrect because the CI parsed a tag number 124, resulting in tarballs of `*-12.0.124.tar.gz`

The entire directory
https://downloads.keyman.com/linux/stable/12.0.50/
needs to be removed.

Note: 12.0.51 seems to be correct.

**Comment by mcdurdin** [comment]
Ok, done.
