### ISSUE TITLE
Feature Request: Add /api/model.php query

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/downloads.keyman.com#26]
Currently, there's a query for current keyboard download links
e.g. https://downloads.keyman.com/api/keyboard/sil_euro_latin

It would be nice to have one for models
e.g. https://downloads.keyman.com/api/model/nrc.en.mtnt

Also, should .htaccess be updated so block /api from being browsable?

**Comment by mcdurdin** [comment]
> Also, should .htaccess be updated so block /api from being browsable?

I'd prefer it to return an index of APIs.
